[manager]
ratio = [1, 2, 5]
sort_by = "extension"
linemode = "mtime"
[preview]
max_width = 5000
max_height = 5000

[opener]
play = [
	{ run = 'iina-cli "$@"', block = true, for = "macos" },
]
edit = [
	{ run = 'nvim "$@"', block = true, for = "macos" },
]
open = [
	{ run = 'open "$@"', desc = "Open" },
]
