#!/bin/bash

options=(
    style=round
    width=5.0
    hidpi=off
    # active_color=0xfff7768e
    # active_color=0xffb9f27c
    # active_color=0xff7aa2f7
    active_color=0xffffffff
    inactive_color=0xff414550
)

/opt/homebrew/bin/borders "${options[@]}"
