fork = true
frame = "buttonless"
title-hidden = true
maximized = true
log = false
idle = true
neovim-bin = "/Users/zexwu/software/nvim-macos-arm64/bin/nvim"
no-multigrid = false
srgb = false
tabs = true
